CREATE TABLE gwas_catalog (
                              "DATE ADDED TO CATALOG" VARCHAR,
                              "PUBMEDID" VARCHAR,
                              "FIRST AUTHOR" VARCHAR,
                              "DATE" VARCHAR,
                              "JOURNAL" VARCHAR,
                              "LINK" VARCHAR,
                              "STUDY" VARCHAR,
                              "DISEASE/TRAIT" VARCHAR,
                              "INITIAL SAMPLE SIZE" VARCHAR,
                              "REPLICATION SAMPLE SIZE" VARCHAR,
                              "REGION" VARCHAR,
                              "CHR_ID" VARCHAR,
                              "CHR_POS" VARCHAR,
                              "REPORTED GENE(S)" VARCHAR,
                              "MAPPED_GENE" VARCHAR,
                              "UPSTREAM_GENE_ID" VARCHAR,
                              "DOWNSTREAM_GENE_ID" VARCHAR,
                              "SNP_GENE_IDS" VARCHAR,
                              "UPSTREAM_GENE_DISTANCE" VARCHAR,
                              "DOWNSTREAM_GENE_DISTANCE" VARCHAR,
                              "STRONGEST SNP-RISK ALLELE" VARCHAR,
                              "SNPS" VARCHAR,
                              "MERGED" VARCHAR,
                              "SNP_ID_CURRENT" VARCHAR,
                              "CONTEXT" VARCHAR,
                              "INTERGENIC" VARCHAR,
                              "RISK ALLELE FREQUENCY" VARCHAR,
                              "P-VALUE" VARCHAR,
                              "PVALUE_MLOG" VARCHAR,
                              "P-VALUE (TEXT)" VARCHAR,
                              "OR or BETA" VARCHAR,
                              "95% CI (TEXT)" VARCHAR,
                              "PLATFORM [SNPS PASSING QC]" VARCHAR,
                              "CNV" VARCHAR,
                              "MAPPED_TRAIT" VARCHAR,
                              "MAPPED_TRAIT_URI" VARCHAR,
                              "STUDY ACCESSION" VARCHAR,
                              "GENOTYPING TECHNOLOGY" VARCHAR
);
